version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
      MYSQL_DATABASE: ecom

  spring-boot-app:
      image: arun071/job-portal-backend
      ports:
        - "8080:8080"
      depends_on:
        - mysql
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecom
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root_password
      restart: always

  react-app:
      image: arun071/job-portal-frontend
      ports:
        - "5173:5173"